docs(Database): Add Import Words & Configuration

diff --git a/config_database b/config_database
--- a/config_database
+++ b/config_database
@@ -1,31 +1,35 @@
 #!/bin/bash
 
 function set_host_db_container_address() {
-    local db_container=$(docker-compose ps | grep database | sed -E "s/\s.+//g")
-    if test -z "$db_container"; then
-        echo "Database container is not found. execute 'docker-compose build database' to create one."
-        exit 1
-    fi
-    local db_address=$(docker inspect -f '{{ range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $db_container)
-    if test -z "$db_address"; then
-        echo "Database container is not running. execute 'docker-compose start database' to run it."
-        exit 1
-    fi
-    host=$db_address
+  db_container=$(docker-compose ps | grep database | sed -E "s/\s.+//g")
+  local db_container
+  if test -z "$db_container"; then
+    echo "Database container is not found. execute 'docker-compose build database' to create one."
+    exit 1
+  fi
+
+  db_address=$(docker inspect -f '{{ range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db_container)
+  local db_address
+  if test -z "$db_address"; then
+    echo "Database container is not running. execute 'docker-compose start database' to run it."
+    exit 1
+  fi
+  db_host=$db_address
 }
 
 echo "Darakbang Engine: Database Configurator"
 echo "Copyright (c) Team StarGarden"
 echo
 
-read -p "DB Host (default: database container): " host
-test -n "$host" || set_host_db_container_address
-read -p "DB User (default: darakbang): " user
-test -n "$user" || user="darakbang"
-read -p "DB Pass (default: kiwi-kawaii): " pass
-test -n "$pass" || pass="kiwi-kawaii"
-read -p "DB Name (default: darakbang): " dbname
-test -n "$dbname" || dbname="darakbang"
+read -r -p "DB Host (default: database container): " db_host
+test -n "$db_host" || set_host_db_container_address
+read -r -p "DB Port (default: 3306): " db_port
+test -n "$db_port" || db_port="3306"
+read -r -p "DB User (default: darakbang): " db_user
+test -n "$db_user" || db_user="darakbang"
+read -r -p "DB Pass (default: kiwi-kawaii): " db_pass
+test -n "$db_pass" || db_pass="kiwi-kawaii"
+read -r -p "DB Name (default: darakbang): " db_name
+test -n "$db_name" || db_name="darakbang"
 
-echo "DATABASE_URL=mysql://${user}:${pass}@${host}/${dbname}" > .env
-echo >> .env
+printf "DATABASE_URL=mysql://%s:%s@%s:%s/%s\n" "$db_user" "$db_pass" "$db_host" "$db_port" "$db_name" | tee .env > /dev/null
